trigger:
  branches:
    include:
      - feature/laravel-echo

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: SSH@0
    inputs:
      sshEndpoint: 'UsCricketTest'
      runOptions: 'inline'
      inline: |
        cd /home/uscricke/public_html/uscricket-test/public/frontendd
        pwd
        eval $(ssh-agent) 2>&1
        ssh-add ~/.ssh/id_rsa 2>&1
    displayName: 'feature/laravel-echo angular branch Deploy via SSH'
